# Example CI/CD workflow for a Spring Boot application
# Location: Application repository at .github/workflows/ci-cd.yml
#
# This is the ONLY workflow file needed in your application repository.
# All the build/test/deploy logic is handled by the shared workflow.

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      # - 'feature/**'
      # - 'feat/**'
      # - 'bugfix/**'
      # - 'fix/**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:      

jobs:
  build-and-deploy:
    # Call the shared workflow for Java applications
    uses: krystof-io/github-workflows/.github/workflows/java-app-build.yml@main
    with:
      # Required: Application name
      app_name: spring-boot-hello
      
      # Optional: Customize as needed (these show non-default values)
      # java_version: '21'                    # Default: '17'
      target_clusters: '["build"]'   # Default: '["app"]'
      # heap_size: '2g'                       # Default: '512m'
      # maven_profiles: 'prod,extra'          # Default: ''
      
    secrets: inherit
    # secrets:
