name: Deployment Unit Tag Build
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - '**'
jobs:
  top-level-deployment-unit:
    uses: krystof-io/common-workflows/.github/workflows/top-level-deployment-unit-build.yaml@main
    secrets: inherit
